CREATE TABLE captcha_codes
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time        TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    code        VARCHAR(255)                             NOT NULL,
    secret_code VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_captcha_codes PRIMARY KEY (id)
);