CREATE TABLE block_history
(
    id         INT8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time       TIMESTAMP with time zone              NOT NULL,
    person_id  INT8                                  NOT NULL,
    post_id    INT8,
    comment_id INT8,
    action     VARCHAR(255)                          NOT NULL,
    CONSTRAINT pk_block_history PRIMARY KEY (id)
);

CREATE TABLE friendship_statuses
(
    id   INT4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time TIMESTAMP with time zone              NOT NULL,
    name VARCHAR(255)                          NOT NULL,
    code INT8,
    CONSTRAINT pk_friendship_statuses PRIMARY KEY (id)
);

CREATE TABLE friendship
(
    id            INT8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_id     INTEGER                               NOT NULL,
    src_person_id INT8                                  NOT NULL,
    dst_person_id INT8                                  NOT NULL,
    CONSTRAINT pk_friendship PRIMARY KEY (id)
);

CREATE TABLE messages
(
    id           INT8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time         TIMESTAMP with time zone              NOT NULL,
    message_text VARCHAR(2048)                         NOT NULL,
    read_status  VARCHAR(255)                          NOT NULL,
    author_id    INT8                                  NOT NULL,
    recipient_id INT8                                  NOT NULL,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);


CREATE TABLE notification_type
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code BOOLEAN                                  NOT NULL,
    name VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_notification_type PRIMARY KEY (id)
);

CREATE TABLE notifications
(
    id                   INT8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sent_time            TIMESTAMP with time zone              NOT NULL,
    contact              VARCHAR(255)                          NOT NULL,
    notification_type_id INT4                                  NOT NULL,
    person_id            INT8                                  NOT NULL,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE TABLE persons
(
    id                  INT8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name          VARCHAR(255)                          NOT NULL,
    last_name           VARCHAR(255)                          NOT NULL,
    reg_date            TIMESTAMP with time zone              NOT NULL,
    birth_date          TIMESTAMP with time zone,
    email               VARCHAR(255)                          NOT NULL,
    phone               VARCHAR(255)                          NOT NULL,
    password            VARCHAR(255)                          NOT NULL,
    photo               VARCHAR(255),
    about               VARCHAR(2048),
    town                VARCHAR(255),
    country             VARCHAR(255),
    confirmation_code   VARCHAR(255)                          NOT NULL,
    is_approved         INTEGER                               NOT NULL,
    messages_permission VARCHAR(255)                          NOT NULL,
    user_type           VARCHAR(255),
    last_online_time    TIMESTAMP with time zone              NOT NULL,
    is_blocked          INTEGER                               NOT NULL,
    CONSTRAINT pk_persons PRIMARY KEY (id)
);
CREATE TABLE post_comments
(
    id           INT8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time         TIMESTAMP with time zone              NOT NULL,
    parent_id    INT8,
    comment_text VARCHAR(2048)                         NOT NULL,
    block_id     INT8,
    post_id      INT8,
    author_id    INT8                                  NOT NULL,
    is_blocked   BOOLEAN                               NOT NULL,
    CONSTRAINT pk_post_comments PRIMARY KEY (id)
);

CREATE TABLE post_files
(
    id      INT8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                          NOT NULL,
    path    VARCHAR(255)                          NOT NULL,
    post_id INT8                                  NOT NULL,
    CONSTRAINT pk_post_files PRIMARY KEY (id)
);

CREATE TABLE post_likes
(
    id        INT8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time      TIMESTAMP with time zone              NOT NULL,
    person_id INT8                                  NOT NULL,
    post_id   INT8                                  NOT NULL,
    CONSTRAINT pk_post_likes PRIMARY KEY (id)
);

CREATE TABLE posts
(
    id         INT8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time       TIMESTAMP with time zone              NOT NULL,
    title      VARCHAR(255)                          NOT NULL,
    post_text  VARCHAR(2048)                         NOT NULL,
    is_blocked INTEGER                               NOT NULL,
    block_id   INT8,
    author_id  INT8                                  NOT NULL,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);

CREATE TABLE tags
(
    id  INT8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tag VARCHAR(255)                          NOT NULL,
    CONSTRAINT pk_tag PRIMARY KEY (id)
);
CREATE TABLE users
(
    id       INT8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                          NOT NULL,
    email    VARCHAR(255)                          NOT NULL,
    password VARCHAR(255)                          NOT NULL,
    type     VARCHAR(255)                          NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE post2tag
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id INT8                                    not null,
    tag_id  INT8                                    not null,
    CONSTRAINT pk_post2tag PRIMARY KEY (id)
);
