
CREATE TABLE block_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  time TIMESTAMP with time zone NOT NULL,
  action VARCHAR(255) NOT NULL,
  person_id INTEGER NOT NULL,
  CONSTRAINT pk_block_history PRIMARY KEY (id)
);

CREATE TABLE friendship_statuses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  time TIMESTAMP with time zone NOT NULL,
  friendship_status_type VARCHAR(255) NOT NULL,
  CONSTRAINT pk_friendship_statuses PRIMARY KEY (id)
);

CREATE TABLE friendships (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  friendship_status_id INTEGER NOT NULL,
  src_person_id INTEGER NOT NULL,
  dst_person_id INTEGER NOT NULL,
  CONSTRAINT pk_friendships PRIMARY KEY (id)
);

CREATE TABLE messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  time TIMESTAMP with time zone NOT NULL,
  message_text VARCHAR(255) NOT NULL,
  read_status VARCHAR(255) NOT NULL,
  author_id INTEGER NOT NULL,
  recipient_id INTEGER NOT NULL,
  CONSTRAINT pk_messages PRIMARY KEY (id)
);

CREATE TABLE notification_type (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  notification_status VARCHAR(255) NOT NULL,
  CONSTRAINT pk_notification_type PRIMARY KEY (id)
);

CREATE TABLE notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  sent_time TIMESTAMP with time zone NOT NULL,
  contact VARCHAR(255) NOT NULL,
  notification_type_id INTEGER NOT NULL,
  person_id INTEGER NOT NULL,
  CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE TABLE persons (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  reg_date TIMESTAMP with time zone NOT NULL,
  birth_date TIMESTAMP with time zone NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  password VARCHAR(255),
  photo VARCHAR(255) NOT NULL,
  about VARCHAR(255),
  town VARCHAR(255) NOT NULL,
  country VARCHAR(255) NOT NULL,
  confirmation_code VARCHAR(255) NOT NULL,
  is_approved INTEGER NOT NULL,
  messages_permission VARCHAR(255) NOT NULL,
  last_online_time TIMESTAMP with time zone NOT NULL,
  is_blocked INTEGER NOT NULL,
  CONSTRAINT pk_persons PRIMARY KEY (id)
);
CREATE TABLE post_comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  time TIMESTAMP with time zone NOT NULL,
  parent_id INTEGER,
  comment_text VARCHAR(255) NOT NULL,
  is_blocked INTEGER NOT NULL,
  block_id INTEGER,
  post_id INTEGER NOT NULL,
  person_id INTEGER NOT NULL,
  CONSTRAINT pk_post_comments PRIMARY KEY (id)
);

CREATE TABLE post_files (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  path VARCHAR(255) NOT NULL,
  post_id INTEGER NOT NULL,
  CONSTRAINT pk_post_files PRIMARY KEY (id)
);

CREATE TABLE post_likes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  time TIMESTAMP with time zone NOT NULL,
  person_id INTEGER NOT NULL,
  post_id INTEGER NOT NULL,
  CONSTRAINT pk_post_likes PRIMARY KEY (id)
);

CREATE TABLE posts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  time TIMESTAMP with time zone NOT NULL,
  title VARCHAR(255) NOT NULL,
  post_text VARCHAR(255) NOT NULL,
  is_blocked INTEGER NOT NULL,
  block_id INTEGER,
  author_id INTEGER NOT NULL,
  CONSTRAINT pk_posts PRIMARY KEY (id)
);

CREATE TABLE tag (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tag VARCHAR(255) NOT NULL,
  CONSTRAINT pk_tag PRIMARY KEY (id)
);
CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id)
);



