CREATE TABLE languages
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_id   BIGINT,
    sent_time TIMESTAMP WITHOUT TIME ZONE,
    entity_id BIGINT,
    info      VARCHAR(255),
    CONSTRAINT pk_languages PRIMARY KEY (id)
);

INSERT INTO languages (type_id, sent_time, entity_id, info) VALUES
                      (1, now(), 1, 'Русский'),
                      (1, now(), 3, 'Український'),
                      (1, now(), 4, 'Беларускі'),
                      (2, now(), 2, 'English'),
                      (3, now(), 5, 'Deutsch'),
                      (3, now(), 6, 'Français'),
                      (3, now(), 7, 'Nederlands'),
                      (2, now(), 8, 'English-USA'),
                      (4, now(), 9, '日本');